/**
 * Truck settings library — URL-based preset definitions.
 *
 * Library entries are defined as share URLs (generated by the "Share current" button).
 * This allows easy copy-paste of configured setups into the library.
 *
 * To add a new entry:
 * 1. Configure the setup in the app
 * 2. Click "Share current" to get a URL
 * 3. Copy the URL into the LIBRARY array below
 */

import type { BoardSetupConfig } from './BoardSetupConfig'
import { deserializeState } from '../utils/urlState'

/** A library entry: a label and the share URL that defines the setup. */
export interface LibraryEntry {
  label: string
  /** Full share URL (e.g. "https://example.com?setup=...") or just the encoded part after "?setup=" */
  url: string
}

/**
 * The truck settings library.
 *
 * Each entry's URL encodes a full app state. The first setup in the URL
 * is used as the preset configuration.
 *
 * To generate a URL: configure a setup, click "Share current", copy the link.
 */
export const LIBRARY: LibraryEntry[] = [
  {
    label: 'Standard RKP 50°',
    url: '?setup=eyJzZXR1cHMiOlt7ImlkIjoicHJlc2V0IiwibmFtZSI6IlN0YW5kYXJkIFJLUCA1MLAiLCJjb2xvciI6IiNlZjQ0NDQiLCJ3aGVlbGJhc2UiOjc2MCwiZnJvbnRUcnVjayI6eyJ0eXBlIjoic2luZ2xlLXBpdm90IiwicGl2b3RBeGlzQW5nbGUiOjUwLCJyYWtlIjowLCJheGxlVG9CYXNlcGxhdGVEaXN0YW5jZSI6MzgsImJhc2VwbGF0ZVRvQm9hcmQiOjQsIndoZWVsRGlhbWV0ZXIiOjE1MCwidHJhY2tXaWR0aCI6MjE4LCJidXNoaW5nTW9tZW50QXJtIjoyNSwicm9hZHNpZGVCdXNoaW5nIjp7InNoYXBlIjoiY29uZSIsImR1cm9tZXRlciI6OTAsImhlaWdodCI6InN0YW5kYXJkIn0sImJvYXJkc2lkZUJ1c2hpbmciOnsic2hhcGUiOiJiYXJyZWwiLCJkdXJvbWV0ZXIiOjkwLCJoZWlnaHQiOiJzdGFuZGFyZCJ9fSwicmVhclRydWNrIjp7InBpdm90QXhpc0FuZ2xlIjo0NywicmFrZSI6MH19XSwicmlkZXJQYXJhbXMiOnsibWFzc0tnIjo4MCwiYm9hcmRUaGlja25lc3NNbSI6MTUsImJvYXJkV2lkdGhNbSI6MjUwLCJjb21IZWlnaHRNIjoxLjA1LCJtYXhMZWFuQW5nbGUiOjQ1fSwiYWN0aXZlU2V0dXBJZCI6InByZXNldCIsInN0ZWVyaW5nTGVhbkFuZ2xlRGVnIjoxMH0',
  },
  {
    label: 'Standard TKP',
    url: '?setup=eyJzZXR1cHMiOlt7ImlkIjoicHJlc2V0IiwibmFtZSI6IlN0YW5kYXJkIFRLUCIsImNvbG9yIjoiI2VmNDQ0NCIsIndoZWVsYmFzZSI6NzQwLCJmcm9udFRydWNrIjp7InR5cGUiOiJzaW5nbGUtcGl2b3QiLCJwaXZvdEF4aXNBbmdsZSI6MzUsInJha2UiOjMsImF4bGVUb0Jhc2VwbGF0ZURpc3RhbmNlIjozMiwiYmFzZXBsYXRlVG9Cb2FyZCI6Mywid2hlZWxEaWFtZXRlciI6MTA0LCJ0cmFja1dpZHRoIjoyMDUsImJ1c2hpbmdNb21lbnRBcm0iOjIwLCJyb2Fkc2lkZUJ1c2hpbmciOnsic2hhcGUiOiJiYXJyZWwiLCJkdXJvbWV0ZXIiOjg4LCJoZWlnaHQiOiJzdGFuZGFyZCJ9LCJib2FyZHNpZGVCdXNoaW5nIjp7InNoYXBlIjoiYmFycmVsIiwiZHVyb21ldGVyIjo4OCwiaGVpZ2h0Ijoic3RhbmRhcmQifX0sInJlYXJUcnVjayI6eyJwaXZvdEF4aXNBbmdsZSI6MzUsInJha2UiOjN9fV0sInJpZGVyUGFyYW1zIjp7Im1hc3NLZyI6ODAsImJvYXJkVGhpY2tuZXNzTW0iOjE1LCJib2FyZFdpZHRoTW0iOjI1MCwiY29tSGVpZ2h0TSI6MS4wNSwibWF4TGVhbkFuZ2xlIjo0NX0sImFjdGl2ZVNldHVwSWQiOiJwcmVzZXQiLCJzdGVlcmluZ0xlYW5BbmdsZURlZyI6MTB9',
  },
  {
    label: 'High-angle RKP 65°',
    url: '?setup=eyJzZXR1cHMiOlt7ImlkIjoicHJlc2V0IiwibmFtZSI6IkhpZ2gtYW5nbGUgUktQIDY1sCIsImNvbG9yIjoiI2VmNDQ0NCIsIndoZWVsYmFzZSI6NzIwLCJmcm9udFRydWNrIjp7InR5cGUiOiJzaW5nbGUtcGl2b3QiLCJwaXZvdEF4aXNBbmdsZSI6NjUsInJha2UiOjAsImF4bGVUb0Jhc2VwbGF0ZURpc3RhbmNlIjo0MiwiYmFzZXBsYXRlVG9Cb2FyZCI6NSwid2hlZWxEaWFtZXRlciI6MTYwLCJ0cmFja1dpZHRoIjoyMzAsImJ1c2hpbmdNb21lbnRBcm0iOjI4LCJyb2Fkc2lkZUJ1c2hpbmciOnsic2hhcGUiOiJjb25lIiwiZHVyb21ldGVyIjo4NSwiaGVpZ2h0IjoidGFsbCJ9LCJib2FyZHNpZGVCdXNoaW5nIjp7InNoYXBlIjoiYmFycmVsIiwiZHVyb21ldGVyIjo4NSwiaGVpZ2h0Ijoic3RhbmRhcmQifX0sInJlYXJUcnVjayI6eyJwaXZvdEF4aXNBbmdsZSI6NTAsInJha2UiOjB9fV0sInJpZGVyUGFyYW1zIjp7Im1hc3NLZyI6ODAsImJvYXJkVGhpY2tuZXNzTW0iOjE1LCJib2FyZFdpZHRoTW0iOjI1MCwiY29tSGVpZ2h0TSI6MS4wNSwibWF4TGVhbkFuZ2xlIjo0NX0sImFjdGl2ZVNldHVwSWQiOiJwcmVzZXQiLCJzdGVlcmluZ0xlYW5BbmdsZURlZyI6MTB9',
  },
  {
    label:'Long Distance Pumper',
    url: '?setup=eyJzZXR1cHMiOlt7ImlkIjoic2V0dXAtMTc4MjE2MDk2NDMzOC0xcmpkc2MiLCJuYW1lIjoiTG9uZy1EaXN0YW5jZSBQdW1wZXIiLCJjb2xvciI6IiMyMmM1NWUiLCJ3aGVlbGJhc2UiOjcyMCwiZnJvbnRUcnVjayI6eyJ0eXBlIjoic2luZ2xlLXBpdm90IiwicGl2b3RBeGlzQW5nbGUiOjY4LCJyYWtlIjoxMiwiYXhsZVRvQmFzZXBsYXRlRGlzdGFuY2UiOjUwLCJiYXNlcGxhdGVUb0JvYXJkIjozMCwid2hlZWxEaWFtZXRlciI6OTUsInRyYWNrV2lkdGgiOjE1MCwiYnVzaGluZ01vbWVudEFybSI6MjUsInJvYWRzaWRlQnVzaGluZyI6eyJzaGFwZSI6ImJhcnJlbCIsImR1cm9tZXRlciI6ODMsImhlaWdodCI6InRhbGwifSwiYm9hcmRzaWRlQnVzaGluZyI6eyJzaGFwZSI6ImJhcnJlbCIsImR1cm9tZXRlciI6ODMsImhlaWdodCI6InN0YW5kYXJkIn19LCJyZWFyVHJ1Y2siOnsicGl2b3RBeGlzQW5nbGUiOjI1LCJyYWtlIjowfX1dLCJyaWRlclBhcmFtcyI6eyJtYXNzS2ciOjk4LCJjb21IZWlnaHRNIjoxLCJib2FyZFRoaWNrbmVzc01tIjoxMSwibWF4TGVhbkFuZ2xlIjoxNSwiYm9hcmRXaWR0aE1tIjoyNDV9LCJhY3RpdmVTZXR1cElkIjoic2V0dXAtMTc4MjE2MDk2NDMzOC0xcmpkc2MiLCJzdGVlcmluZ0xlYW5BbmdsZURlZyI6MTV9'
  }
]

/**
 * Extract the first setup configuration from a library entry URL.
 *
 * @param entry - The library entry containing the URL.
 * @returns The BoardSetupConfig, or null if the URL is invalid.
 */
export function getSetupFromLibraryEntry(entry: LibraryEntry): Omit<BoardSetupConfig, 'id' | 'name' | 'color'> | null {
  // Extract the encoded part from the URL (after "?setup=")
  const match = entry.url.match(/[?&]setup=([^&]+)/)
  if (!match) return null

  const encoded = match[1]
  const state = deserializeState(encoded)
  if (!state || state.setups.length === 0) return null

  // Return the first setup without id, name, color (those will be assigned when instantiated)
  const { id: _id, name: _name, color: _color, ...config } = state.setups[0]
  return config
}
